### ISSUE TITLE
Right clic on GNU/Linux

### ISSUE THREAD

**Issue by bugsysop** [julianoappelklein/hokus#14]
Can't paste (or cut) using right mouse button on Ubuntu LTS

**Comment by adrinux** [comment]
Out of interest did you compile yourself or download a release?

**Comment by adrinux** [comment]
Just used apt to remove hokus-cms and re-compiled and installed. Same issue is present. Can use keyboard cut/copy/paste and can middle click to paste having selected some text but the expected pop-up menu never appears.

**Comment by julianoappelklein** [comment]
I know how to fix this. Is simple and I intend to do it today.

**Comment by julianoappelklein** [comment]
@adrinux and @bugsysop,
I pushed the changes to fix this ticket. It took more time than expected because I decided to update some modules.

I don't have the time to generate the releases right now, but I will soon.

Look, I need your help in [another thing](https://github.com/julianoappelklein/hokus/issues/16). Can you help me?
