### ISSUE TITLE
Mac: "Please select a workspace" button does not do anything

### ISSUE THREAD

**Issue by kmddevdani** [julianoappelklein/hokus#20]
Hey, thank you for creating and maintaining this project!

When I run Hokus on Mac, there is this "Current Workspace" headline in the left menu bar, and the "Please select a workspace" button underneath. Unfortunately, neither the button itself nor the little gearwheel cause any action. How can I create or select a workspace?

**Comment by julianoappelklein** [comment]
First, you have to create a new site (using the Folder Source type, the only option right now).

Weh you select this new website, you'll see in the available workspaces in the right column. For Folder Source you only have one workspace, by design.

In the GitSource (under development), every branch is a workspace.

Does this make sense for you now?
Do you have any suggestion to make this first step more intuitive?
Maybe I can just hide the WorkspaceWidget an replace it with some instructions.

**Comment by kmddevdani** [comment]
Thank you for your quick reply. I cannot push the "Submit" button in the "New Site" popup window. My settings are as follows:

- Key: MySite
- Source Type: Folder
- Site Folder: /Users/me/Documents/mysite (this is an empty folder)
- Theme Repository URL: <empty>

Even if I fill a value into the Theme Repository URL, the "submit" button remains greyed out. 
Would you know why this could be?

Unfortunately, I do not really know what belongs into the "Theme Repository URL" field - could you give an example, please?

**Comment by julianoappelklein** [comment]
You are welcome.

The problem is the site key. It only accepts lowercase letters. This is described in the texfield placeholder.
The UI really needs more tunning and this kind of feedback is very useful.

The Theme Repositore URL is the Hugo theme you want to use. You can find a list here https://themes.gohugo.io/
It will download the theme and include it in your brand-new site. In the future, I hope, it will also include the Hokus configuration for the theme. This way, the UI will be fully configured.

**Comment by julianoappelklein** [comment]
This is a valid Theme Repository URL:
https://github.com/spf13/hyde.git

**Comment by kmddevdani** [comment]
Oh, sure - my apologies. Yes, it says that in the placeholder, definitely. My bad. Thank you! It seems to work, now. Great!

I had found the themes already, but was not sure about the URL. Would it be the repository URL? Or some zip file URL? For sure, this should be clear to anyone who has been working with Hugo for a while already. Thanks again!

**Comment by julianoappelklein** [comment]
My pleasure.
I will create a new issue based on this thread.
If the UI is not clear for you, certainly it's not clear for more people.
Don't hesitate to ask for more help.
