### ISSUE TITLE
How to compile 

### ISSUE THREAD

**Issue by bugsysop** [julianoappelklein/hokus#4]
Can you provide some information on how to compile for Mac or GNU/Linux ?

**Comment by julianoappelklein** [comment]
Hello there, yes I can.

In fact, I already successfully compiled Hokus for Linux (Ubunto 17), but some key features haven't worked properly. I would recomment you to wait a little more.

And to be honest, the building process is about to change. I'll probably have to include a new compilation step since today I'm including a new library to handle Git operations. This library use native code, so the building process got a little bit more complicated.

After this new feature (a way to start a fresh site just pointing to a theme repository), I'll probably work in the Linux version bugs and then I will have a proper compilation process.

**BUT**, if you can't wait, the current building process for Linux is:

- Install NodeJS: `sudo apt-get nodejs`
- Install NPM: `sudo apt-get npm`
- Set the current directory to the root directory.
- Execute `npm install`
- Execute `npm run dist-linux`

I'll let this issue open to remind me tell you when the process is more consolidated.

**Comment by bugsysop** [comment]
Thanks !

**Comment by adrinux** [comment]
FWIW
Just tried to compile on Ubuntu 18.04 following above and needed libssl-dev for node-git.
```
sudo apt-get install libssl-dev
```
Other that complilation and install worked. App still has some rough edges, obviously, but very impressive.

**Comment by julianoappelklein** [comment]
@adrinux, thank you for sharing the information, it will save me some time.
I'm setting up my Linux (Ubuntu 18.04 as well) development environment to work on those rough edges.
Don't be afraid to point out the problems you found. You can always open an issue.

**Comment by julianoappelklein** [comment]
@bugsysop,
I've included the compilation steps in the README.md.
I also fixed the two main Linux bugs and successfully build a deb installer (on Ubuntu 18.04).
I'll release a new version soon, for Windows and, **finally, for Linux**.

**Comment by julianoappelklein** [comment]
And please, with you need any help, just ask.

**Comment by julianoappelklein** [comment]
Binaries for Linux are available (Debian package).

https://github.com/julianoappelklein/hokus/releases

**Comment by julianoappelklein** [comment]
@bugsysop - binaries for Mac are also available now!
